### PR TITLE
Add image uploading functionality

### PR DESCRIPTION
**Pull request by Silvyre**
Resolves SenecaCollegeBTSProjects/Group_17#27: introduces minimal image uploading functionality.

This functionality has been added to an `/upload` frontend route for demonstrative purposes.

All images are currently uploaded to an [`images/` Firebase Cloud Storage folder](https://console.firebase.google.com/project/inventurbo-f0eca/storage/inventurbo-f0eca.appspot.com/files~2Fimages).

@VictorHadziristic please feel welcome to use this to help implement avatar uploading!

* * * 

uploaddemo

### CODE REVIEW

**Comment by Silvyre** [comment]
> 
> 
> Hi Rafi, This is amazing!
> 
> I suggest some architectural changes to your work that I think will benefit everyone who is going to use it: Let's separate your `uplaod()` method into an Angular Service. The method will receive a file (the `event.target.files[0]` thing) as argument and return an `Observable<string>` represnets the download URL.
> 
> If you can, please adapt your example component to use the new service, too.

Good idea, let me try...

**Comment by vitokhangnguyen** [comment]
Also, although not required, I think that when a user keeps changing profile image will result in a large number of useless files in our system. Can we have a method to remove or replace the existing file, too?

**Comment by Silvyre** [comment]
> 
> 
> Also, although not required, I think that when a user keeps changing profile image will result in a large number of useless files in our system. Can we have a method to remove or replace the existing file, too?

I think uploading a file with the same pathname as another will overwrite that file. For avatars, we could make the filename non-unique, e.g. `${uid}.png`

**Comment by vitokhangnguyen** [comment]
@Silvyre That is perfect! Good job, let's make the changes above and merge this PR. Thank you!

**Comment by Silvyre** [comment]
> 
> 
> @Silvyre That is perfect! Good job, let's make the changes above and merge this PR. Thank you!

Khang and I agreed that development of the image upload service will occur in a separate branch/PR: 
https://github.com/rayshroom/InvenTurboFrontend/tree/image-upload-service

Merging this reviewed PR, as it accomplishes what it set out to do.

**Comment by vitokhangnguyen** [comment]
Can you do a PR for that branch, too? Eventually, we will want that branch landed, too.

**Comment by Silvyre** [comment]
> 
> 
> Can you do a PR for that branch, too? Eventually, we will want that branch landed, too.

The `image-upload-service` conflicts with master (in that it refactors the `image-upload` component to use a service). I think we should develop `image-upload-service` separately from master until its functionality is finished (it currently has some bugs to work out).

**Comment by vitokhangnguyen** [comment]
Well, my intention is to have that service in soon so I can use it in my Add Product Feature. You don't think it is possible?

**Comment by Silvyre** [comment]
Feel welcome to pull commit https://github.com/rayshroom/InvenTurboFrontend/commit/fb6ad185132f635c694fe677c64c9a3607b999dc (or copy its files) into your `Add Product Feature` development branch! I just want to avoid changes to the `image-upload` module until I can present it to the professor on Thursday.

**Pull request merged**
